version: "3.5" # Use version 3.5 syntax
services: # Here we define our service(s)
    db:
        container_name: mongodb-test # Container name
        image: mongo # image name to start/build
        ports: # Port mapping
            - "2717:27017"
        volumes: # Volume binding
            - "~/example:/data/db"
    cache-db:
        container_name: redis-test # Container name
        image: redis
        ports:
            - "6379:6379"
        volumes: # Volume binding
            - "/opt/redis/data:/data"
    golang-restapi: # The name of the service
        build:
            context: WebAPI
            dockerfile: Dockerfile # Location of our Dockerfile
        image: despenrado/golang-restapi:prod.0.1
        container_name: spring-webapi # Container name
        depends_on: # start after
            - cache-db
            - db
        ports:
            - "8081:8081"
        links: # list mapping: service_name:name_how_will_see_your_program
            - "db:mymongo"
            - "cache-db:myredis"
