/opt/miktex/bin/miktex-pdftex -undump=pdflatex Dyplom.tex
/opt/miktex/bin/miktex-pdftex -undump=pdflatex Dyplom.tex
/opt/miktex/bin/miktex-pdftex -undump=pdflatex Dyplom.tex
/opt/miktex/bin/miktex-bibtex Dyplom